### ISSUE TITLE
 process has died

### ISSUE THREAD

**Issue by RoseWillow** [brytsknguyen/LIO-SAM#3]
[lio_sam_mapOptmization-5] process has died [pid 11866, exit code -11, cmd /home/dnc/issl_ws/devel/lib/lio_sam/lio_sam_mapOptmization __name:=lio_sam_mapOptmization __log:=/home/dnc/.ros/log/1fffa198-67ff-11ed-93ab-517787db1e13/lio_sam_mapOptmization-5.log].
log file: /home/dnc/.ros/log/1fffa198-67ff-11ed-93ab-517787db1e13/lio_sam_mapOptmization-5*.log

**Comment by brytsknguyen** [comment]
Hi, can you describe your system?

Ubuntu version
ROS version
OpenCV
GTSAM version (do install GTSAM following this instruction from https://github.com/TixiaoShan/LIO-SAM)
![image](https://user-images.githubusercontent.com/13504903/202852379-efe61384-066e-46d5-98bb-7f8324e6e7ff.png)

**Comment by RoseWillow** [comment]
> Hi, can you describe your system?
> 
> Ubuntu version ROS version OpenCV GTSAM version (do install GTSAM following this instruction from https://github.com/TixiaoShan/LIO-SAM) ![image](https://user-images.githubusercontent.com/13504903/202852379-efe61384-066e-46d5-98bb-7f8324e6e7ff.png)

I use Ubuntu 20.04 with ROS Noetic， and I install GTSAM 4.0.3.
Thank you for your reply, I will have a try on Ubuntu 18.04.
